## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
##
## rxyhn's starship configuration
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

format = "$all"
right_format = """$git_branch$git_status$cmd_duration$directory"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [](#859900)"
error_symbol = " [](#dc322f)"
vicmd_symbol = "[  ](#d33682)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:#eee8d5 bg:none)[$duration]($style)[](fg:#eee8d5 bg:#eee8d5)[](fg:#268bd2 bg:#eee8d5)[](fg:#eee8d5 bg:#268bd2)[](fg:#268bd2 bg:none) "
disabled = false
style = "fg:#657b83 bg:#eee8d5"

[directory]
format = "[](fg:#eee8d5 bg:none)[$path]($style)[](fg:#eee8d5 bg:#eee8d5)[](fg:#859900 bg:#eee8d5)[](fg:#eee8d5 bg:#859900)[](fg:#859900 bg:none)"
style = "fg:#657b83 bg:#eee8d5"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[](fg:#eee8d5 bg:none)[$branch]($style)[](fg:#eee8d5 bg:#eee8d5)[](fg:#d33682 bg:#eee8d5)[](fg:#eee8d5 bg:#d33682)[](fg:#d33682 bg:none) "
style = "fg:#657b83 bg:#eee8d5"

[git_status]
format="[](fg:#eee8d5 bg:none)[$all_status$ahead_behind]($style)[](fg:#eee8d5 bg:#eee8d5)[](fg:#2aa198 bg:#eee8d5)[](fg:#eee8d5 bg:#2aa198)[](fg:#2aa198 bg:none) "
style = "fg:#657b83 bg:#eee8d5"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
